/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.frames;

import java.beans.PropertyVetoException;
import java.util.Date;
import java.util.LinkedList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uam.pvoe.shared.Shared;
import uam.pvoe.operations.UserData;
import uam.pvoe.operations.CategoryLoading;
import uam.pvoe.operations.TableLoading;

/**
 * This is the Consultation class, here are the interface and the methods which
 * allow us to fill labels and tables. Also, here are the methods that run when
 * a button is pressed.
 * @author pedro
 */
public class Consultation extends javax.swing.JInternalFrame {

    /**
     * Creates new form
     */
    public Consultation() {
        initComponents();
        loadData();
        cmbCategoryS.removeAllItems();
        fillList();
        fillInitialTable();
    }

    /*This method is used to fill the list with the material names*/
    private void fillList() {
        CategoryLoading filling = new CategoryLoading();
        LinkedList<String> list = filling.fillCat();

        for (int i = 0; i < list.size(); i++) {
            cmbCategoryS.addItem(list.get(i));
        }
    }

    /*This method is used to assign date and user to their labels*/
    private void loadData() {
        UserData data = new UserData();
        data.userName(Shared.login);
        Date d = new Date();

        lblName2C.setText(Shared.userName);
        lblDate2C.setText(String.valueOf(d.toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNameC = new javax.swing.JLabel();
        lblName2C = new javax.swing.JLabel();
        lblDateC = new javax.swing.JLabel();
        lblDate2C = new javax.swing.JLabel();
        lblTittleC = new javax.swing.JLabel();
        cmbCategoryS = new javax.swing.JComboBox<>();
        btnAccept = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblElementsC2 = new javax.swing.JTable();

        lblNameC.setText("User:");

        lblName2C.setText("jLabel2");

        lblDateC.setText("Date");

        lblDate2C.setText("jLabel4");

        lblTittleC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTittleC.setText("the toal");

        cmbCategoryS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        tblElementsC2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(tblElementsC2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblNameC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName2C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDateC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate2C)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAccept)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbCategoryS, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(516, 516, 516))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTittleC)
                        .addGap(555, 555, 555))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameC)
                    .addComponent(lblName2C)
                    .addComponent(lblDateC)
                    .addComponent(lblDate2C))
                .addGap(32, 32, 32)
                .addComponent(lblTittleC)
                .addGap(56, 56, 56)
                .addComponent(cmbCategoryS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(btnAccept)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*This method is used to display the titles of the materials*/
    private void fillInitialTable() {
        DefaultTableModel model = new DefaultTableModel(0, 0);
        tblElementsC2.setModel(model);
        TableLoading filling = new TableLoading();
        Vector<String> titlesList = new Vector();
        titlesList = filling.columnsTitle();

        for (int i = 0; i < titlesList.size(); i++) {
            String title = titlesList.get(i);
            model.addColumn(title);
        }
    }
    
    /*This methods is used to show the subjects when the Accept button is pressed*/
    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        DefaultTableModel model = new DefaultTableModel(0, 0);
        tblElementsC2.setModel(model);
        TableLoading filling = new TableLoading();
        Vector<String> titlesList = new Vector();
        titlesList = filling.columnsTitle();

        for (int i = 0; i < titlesList.size(); i++) {
            String title = titlesList.get(i);
            model.addColumn(title);
        }

        if (cmbCategoryS.getSelectedItem() == "STEM") {
            Vector rows = filling.cellsElementsSTEM();
            model.setDataVector(rows, titlesList);

            tblElementsC2.setModel(model);
        }
        else if(cmbCategoryS.getSelectedItem() == "Art"){
            Vector rows = filling.cellsElementsArt();
            model.setDataVector(rows, titlesList);

            tblElementsC2.setModel(model);
        }
        else if(cmbCategoryS.getSelectedItem() == "Social Sciences"){
            Vector rows = filling.cellsElementsSS();
            model.setDataVector(rows, titlesList);

            tblElementsC2.setModel(model);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select a category",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JComboBox<String> cmbCategoryS;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate2C;
    private javax.swing.JLabel lblDateC;
    private javax.swing.JLabel lblName2C;
    private javax.swing.JLabel lblNameC;
    private javax.swing.JLabel lblTittleC;
    private javax.swing.JTable tblElementsC2;
    // End of variables declaration//GEN-END:variables
}
