/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.frames;

import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import uam.pvoe.shared.Shared;
import uam.pvoe.operations.UserData;
import uam.pvoe.operations.TableLoading;

/**
 * This class is used to display the main menu window.
 * @author pedro
 */
public class MainMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuPrincipal
     * This is also used to call the methods.
     */
    public MainMenu() {
        initComponents();
        loadData();
        fillTable();
    }
    
    /**
     * This method is used to fill the information table of this window.
     */
    private void fillTable(){
        DefaultTableModel model = new DefaultTableModel(0, 0);
        tblContent.setModel(model);
        TableLoading filling = new TableLoading();
        Vector<String> titleList = new Vector();
        titleList = filling.columnsTitleP();

        for (int i = 0; i < titleList.size(); i++) {
            String title = titleList.get(i);
            model.addColumn(title);
        }


        Vector rows = filling.cellsElementsP();
        model.setDataVector(rows, titleList);
        
        tblContent.setModel(model);
    }
    
    private void loadData(){
        UserData data = new UserData();
        data.userName(Shared.login);
        Date d = new Date();
        
        lblUsrN.setText(Shared.userName);
        lblCurrDate.setText(String.valueOf(d.toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsrM = new javax.swing.JLabel();
        lblUsrN = new javax.swing.JLabel();
        lblSystemB = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblInventoryN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContent = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        lblCurrDate = new javax.swing.JLabel();

        lblUsrM.setText("User:");

        lblUsrN.setText("jLabel2");

        lblSystemB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSystemB.setText("Library Control System");

        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblWelcome.setText("Welcome to Main Menu of The Book Inventory");

        lblInventoryN.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lblInventoryN.setText("The Inventory in numbers");

        tblContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblContent);

        lblDate.setText("Fecha:");

        lblCurrDate.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblUsrM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsrN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurrDate)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWelcome)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(539, 539, 539)
                            .addComponent(lblInventoryN))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(410, 410, 410)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(571, 571, 571)
                            .addComponent(lblSystemB))))
                .addContainerGap(484, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsrM)
                    .addComponent(lblUsrN)
                    .addComponent(lblDate)
                    .addComponent(lblCurrDate))
                .addGap(48, 48, 48)
                .addComponent(lblSystemB)
                .addGap(31, 31, 31)
                .addComponent(lblWelcome)
                .addGap(54, 54, 54)
                .addComponent(lblInventoryN)
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrDate;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblInventoryN;
    private javax.swing.JLabel lblSystemB;
    private javax.swing.JLabel lblUsrM;
    private javax.swing.JLabel lblUsrN;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblContent;
    // End of variables declaration//GEN-END:variables
}
