/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.frames;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import uam.pvoe.classes.Material;
import uam.pvoe.shared.Shared;
import uam.pvoe.operations.UserData;
import uam.pvoe.operations.CategoryLoading;
import uam.pvoe.operations.MaterialRegistration;

/**
 * This is the NewData class, which contains the methods for its window.
 * @author pedro
 */
public class NewData extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alta
     */
    public NewData() {
        initComponents();
        loadData();
        cmbMaterialTypeAlt.removeAllItems();
        cmbSubjectMat.removeAllItems();
        fillList();
        fillList2();
    }

    /**
     * This method is used to fill the combobox with the type materials.
     */
    private void fillList() {
        CategoryLoading filling = new CategoryLoading();
        LinkedList<String> list = filling.fillMatType();

        for (int i = 0; i < list.size(); i++) {
            cmbMaterialTypeAlt.addItem(list.get(i));
        }
    }

    /**
     * This method is used to fill the combobox with the name of the materials.
     */
    private void fillList2() {
        CategoryLoading filling = new CategoryLoading();
        LinkedList<String> list = filling.fillCat();

        for (int i = 0; i < list.size(); i++) {
            cmbSubjectMat.addItem(list.get(i));
        }
    }

    /**
     * This method is used to assign user and date to their labels.
     */
    private void loadData() {
        UserData data = new UserData();
        data.userName(Shared.login);
        Date d = new Date();

        lblUserAlt2.setText(Shared.userName);
        lblDateAlt2.setText(String.valueOf(d.toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserAlt = new javax.swing.JLabel();
        lblUserAlt2 = new javax.swing.JLabel();
        lblDateAlt = new javax.swing.JLabel();
        lblDateAlt2 = new javax.swing.JLabel();
        lblTitleAlt = new javax.swing.JLabel();
        lblMaterialAlt = new javax.swing.JLabel();
        cmbMaterialTypeAlt = new javax.swing.JComboBox<>();
        lblLastName1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtLastName1 = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblSubjectMat = new javax.swing.JLabel();
        cmbSubjectMat = new javax.swing.JComboBox<>();
        lblTitleMat = new javax.swing.JLabel();
        txtTitleMat = new javax.swing.JTextField();
        lblIssuesNumber = new javax.swing.JLabel();
        txtIssuesNumer = new javax.swing.JTextField();
        lblMaterialKey = new javax.swing.JLabel();
        txtMaterialKey = new javax.swing.JTextField();
        btnAccept = new javax.swing.JButton();

        lblUserAlt.setText("User");

        lblUserAlt2.setText("jLabel2");

        lblDateAlt.setText("Date");

        lblDateAlt2.setText("jLabel4");

        lblTitleAlt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitleAlt.setText("Register A New Material");

        lblMaterialAlt.setText("Material Type");

        cmbMaterialTypeAlt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblLastName1.setText("Author's Last Name");

        lblName.setText("Author's Name");

        lblSubjectMat.setText("Subject");

        cmbSubjectMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTitleMat.setText("Title");

        lblIssuesNumber.setText("Issues Number");

        lblMaterialKey.setText("Batch");

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblUserAlt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserAlt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDateAlt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateAlt2)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAccept)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaterialAlt)
                            .addComponent(cmbMaterialTypeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSubjectMat, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(232, 232, 232)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIssuesNumber)
                                    .addComponent(txtIssuesNumer, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblLastName1))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSubjectMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitleMat, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitleMat))
                        .addGap(554, 554, 554))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaterialKey)
                            .addComponent(txtMaterialKey, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitleAlt)
                .addGap(534, 534, 534))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserAlt)
                    .addComponent(lblUserAlt2)
                    .addComponent(lblDateAlt)
                    .addComponent(lblDateAlt2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblTitleAlt)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaterialAlt)
                            .addComponent(lblLastName1)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMaterialTypeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubjectMat)
                            .addComponent(lblTitleMat)
                            .addComponent(lblIssuesNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitleMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIssuesNumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(cmbSubjectMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(lblMaterialKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaterialKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnAccept)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is used to get the written information from the textboxes and
     * comboboxes and then store it in the .dat files.
     * @param evt 
     */
    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        Material mat2 = new Material();
        MaterialRegistration r = new MaterialRegistration();
        String err = null;
        
        if ((String) cmbSubjectMat.getSelectedItem() == "STEM") {
            try {
                mat2.setIssueNum(Integer.parseInt(txtIssuesNumer.getText()));
                mat2.setType((String) cmbMaterialTypeAlt.getSelectedItem());
                mat2.setAuthorLastN(txtLastName1.getText());
                mat2.setAuthorName(txtName.getText());
                mat2.setSubject((String) cmbSubjectMat.getSelectedItem());
                mat2.setTitle(txtTitleMat.getText());
                mat2.setKey(txtMaterialKey.getText());
                mat2.setKey(txtMaterialKey.getText());
                err = r.STEMRegistration2(mat2);
                
                if (err == "An error has ocurred") {
                    JOptionPane.showMessageDialog(this, "An error has occurred, contact the administrator",
                            "ERROR", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "The material has been registered successfully",
                            "Material registration", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Provide a valid character in Issues Number, please",
                        "Material registration", JOptionPane.ERROR_MESSAGE);
            }

        } else if((String) cmbSubjectMat.getSelectedItem() == "Arte"){
            try {
                mat2.setIssueNum(Integer.parseInt(txtIssuesNumer.getText()));
                mat2.setType((String) cmbMaterialTypeAlt.getSelectedItem());
                mat2.setAuthorLastN(txtLastName1.getText());
                mat2.setAuthorName(txtName.getText());
                mat2.setSubject((String) cmbSubjectMat.getSelectedItem());
                mat2.setTitle(txtTitleMat.getText());
                mat2.setKey(txtMaterialKey.getText());
                mat2.setKey(txtMaterialKey.getText());
                err = r.artRegistration(mat2);
                
                if (err == "An error has ocurred") {
                    JOptionPane.showMessageDialog(this, "An error has occurred, contact the administrator",
                            "ERROR", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "The material has been registered successfully",
                            "Material registration", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Provide a valid character in Issues Number, please",
                        "Material registration", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if((String) cmbSubjectMat.getSelectedItem() == "Social Sciences"){
            try {
                mat2.setIssueNum(Integer.parseInt(txtIssuesNumer.getText()));
                mat2.setType((String) cmbMaterialTypeAlt.getSelectedItem());
                mat2.setAuthorLastN(txtLastName1.getText());
                mat2.setAuthorName(txtName.getText());
                mat2.setSubject((String) cmbSubjectMat.getSelectedItem());
                mat2.setTitle(txtTitleMat.getText());
                mat2.setKey(txtMaterialKey.getText());
                mat2.setKey(txtMaterialKey.getText());
                err = r.ssRegistration(mat2);
                
                if (err == "An error has ocurred") {
                    JOptionPane.showMessageDialog(this, "An error has occurred, contact the administrator",
                            "ERROR", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "The material has been registered successfully",
                            "Material registration", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Provide a valid character in Issues Number, please",
                        "Material registration", JOptionPane.ERROR_MESSAGE);
            }
        }

        

    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JComboBox<String> cmbMaterialTypeAlt;
    private javax.swing.JComboBox<String> cmbSubjectMat;
    private javax.swing.JLabel lblDateAlt;
    private javax.swing.JLabel lblDateAlt2;
    private javax.swing.JLabel lblIssuesNumber;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblMaterialAlt;
    private javax.swing.JLabel lblMaterialKey;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSubjectMat;
    private javax.swing.JLabel lblTitleAlt;
    private javax.swing.JLabel lblTitleMat;
    private javax.swing.JLabel lblUserAlt;
    private javax.swing.JLabel lblUserAlt2;
    private javax.swing.JTextField txtIssuesNumer;
    private javax.swing.JTextField txtLastName1;
    private javax.swing.JTextField txtMaterialKey;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTitleMat;
    // End of variables declaration//GEN-END:variables
}
